CREATE TABLE COMPATIBILIDADES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID BIGINT NOT NULL,
    VAGA_ID BIGINT NOT NULL,
    COMPATIBILIDADE INT NOT NULL,
    MELHOR BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_COMPAT_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID),
    CONSTRAINT FK_COMPAT_VAGA FOREIGN KEY (VAGA_ID) REFERENCES VAGAS(VAGA_ID)
);