CREATE TABLE USUARIOS (
    USUARIO_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA_HASH VARCHAR(255) NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE VAGAS (
    VAGA_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(150) NOT NULL,
    DESCRICAO TEXT,
    REQUISITOS VARCHAR(1000)
);
CREATE TABLE CURSOS (
    CURSO_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(150) NOT NULL,
    DESCRICAO TEXT,
    DURACAO_HORAS DECIMAL(5,2)
);
CREATE TABLE COMPETENCIAS (
    COMPETENCIA_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) UNIQUE NOT NULL,
    DESCRICAO VARCHAR(500)
);