CREATE TABLE PERFIS (
    PERFIL_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID BIGINT UNIQUE NOT NULL,
    RESUMO VARCHAR(1000),
    ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);
CREATE TABLE INSCRICOES (
    INSCRICAO_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID BIGINT NOT NULL,
    CURSO_ID BIGINT NOT NULL,
    DATA_INSCRICAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'EM PROGRESSO',
    CONSTRAINT FK_INSC_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID),
    CONSTRAINT FK_INSC_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(CURSO_ID),
    CONSTRAINT UK_INSC_UNICA UNIQUE (USUARIO_ID, CURSO_ID)
);
CREATE TABLE USUARIO_COMPETENCIAS (
    USUARIO_ID BIGINT NOT NULL,
    COMPETENCIA_ID BIGINT NOT NULL,
    NIVEL_PONTUACAO DECIMAL(2,1) NOT NULL,
    PRIMARY KEY (USUARIO_ID, COMPETENCIA_ID),
    CONSTRAINT FK_UC_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID),
    CONSTRAINT FK_UC_COMPETENCIA FOREIGN KEY (COMPETENCIA_ID) REFERENCES COMPETENCIAS(COMPETENCIA_ID),
    CONSTRAINT CK_PONTUACAO CHECK (NIVEL_PONTUACAO >= 1.0 AND NIVEL_PONTUACAO <= 5.0)
);