CREATE TABLE APP_AUDITORIA (
    AUDITORIA_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME_TABELA VARCHAR(50) NOT NULL,
    OPERACAO VARCHAR(10) NOT NULL,
    DADOS_ANTIGOS TEXT,
    DADOS_NOVOS TEXT,
    ALTERADO_POR VARCHAR(100),
    DATA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- Aqui você poderia criar triggers para INSERT/UPDATE/DELETE se quiser monitorar alterações